<?php 
$page = (!empty($_GET['page-id'])) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? $admin::secure($_GET['query']) : '';
$filter_type    = '';
$admin::$db->pageLimit = 20;


if (!empty($filter_keyword)) {
    $sq = $admin::$db->subQuery();
    $sq->where('referrer',0,'!=');
    $sq->where('username',"%$filter_keyword%",'LIKE');
    $sq->where('email',"%$filter_keyword%",'LIKE','OR');
    $sq->where('fname',"%$filter_keyword%",'LIKE','OR');
    $sq->where('lname',"%$filter_keyword%",'LIKE','OR');
    $sq->where('user_id',"$filter_keyword",'=','OR');
    $sq->get(T_USERS, null, 'referrer');
    $admin::$db->where('referrer', $sq, 'IN');
	$users = $admin::$db->orderBy('count', 'DESC')->groupBy('referrer')->paginate(T_USERS, $page, 
        array(
            'referrer as user_id',
            'count(`referrer`) as count')); 
} 

else {
    $admin::$db->where('referrer',0,'!=');
	$users = $admin::$db->orderBy('count', 'DESC')->groupBy('referrer')->paginate(T_USERS, $page, 
        array(
            'referrer as user_id',
            'count(`referrer`) as count')); 
}
 
if (($page > $admin::$db->totalPages) && !empty($_GET['page-id'])) {
	header("Location: " . pxp_acp_link('manage-users'));
	exit();
}
?>
<div class="clearfix">
    <div class="block-header">
        <h2 class="breadcrumb">Users <i class="material-icons">keyboard_arrow_right</i> Manage Affiliates</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Most active Affiliates and Referrers</h2>
                </div>
                <div class="body">
                    <div class="clearfix">
                        <div class="col-md-6" style="margin-bottom:0;">
                            <form method="get" action="<?php echo pxp_acp_link('manage-referrers'); ?>">
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <input type="text" name="query" id="query" class="form-control"  value="<?php echo($filter_keyword); ?>">
                                                <label class="form-label search-form">Search for ID, Keyword, E-mail, Username, First Name, Last Name</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <button class="btn btn-info">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover table-users">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Username</th>
                                    <th>E-mail</th>
                                    <th>Phone</th>
                                    <th><i class="material-icons">group_add</i></th> 
                                    <th>Status</th> 
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                    if (!empty($users)) {
                                        foreach ($users as $key => $user_data) {
                                            $context['user']  = $admin->userData($admin->getUserDataById($user_data->user_id));
                                            $context['user']  = o2array($context['user']);
                                            $context['count'] = $user_data->count;
                                            echo $admin->loadPage('manage-referrers/list');
                                        }
                                    }

                                    else{
                                        echo $admin::createHtmlEl('tr',null,$admin::createHtmlEl('td',array(
                                            'colspan' => 6,
                                            'class' => 'empty-table',
                                        ),"No users found"));
                                    } 
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <?php if (!empty($users)): ?>      
                        <div class="clearfix">
                            <nav class="clearfix pagination-nav">
                                <div class="left col-md-5">
                                    <ul class="pagination">
                                        <li>
                                            <span>
                                                <?php echo "Showing $page out of " . $admin::$db->totalPages; ?>
                                            </span>
                                        </li>
                                    </ul>
                                </div>

                                <div class="clearfix col-md-7 right">
                                    <ul class="pagination pull-right">
                                        <li>
                                            <a href="<?php echo pxp_acp_link('manage-users?page-id=1'); ?>" class="waves-effect" title='First Page'>
                                                <i class="material-icons">first_page</i>
                                            </a>
                                        </li>

                                        <?php if ($page > 1) { ?>
                                        <li>
                                            <a href="<?php echo pxp_acp_link('manage-users?page-id=' . ($page - 1)); ?>" class="waves-effect" title='Previous Page'>
                                                <i class="material-icons">chevron_left</i>
                                            </a>
                                        </li>
                                        <?php } ?>

                                        <?php 
                                            $nums = 0;
                                            $nums_pages = ($page > 4) ? ($page - 4) : $page;
                                            for ($i=$nums_pages; $i <= $admin::$db->totalPages; $i++) { 
                                            if ($nums < 20) {?>

                                            <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                                <a href="<?php echo pxp_acp_link('manage-users?page-id=' . ($i)); ?>" class="waves-effect">
                                                <?php echo $i ?>
                                                </a>
                                            </li>
                                            <?php } $nums++;
                                            }
                                        ?>

                                        <?php if ($admin::$db->totalPages > $page) { ?>
                                        <li>
                                            <a href="<?php echo pxp_acp_link('manage-users?page-id=' . ($page + 1)); ?>" class="waves-effect" title="Next Page">
                                                <i class="material-icons">chevron_right</i>
                                            </a>
                                        </li>
                                        <?php } ?>

                                        <li>
                                            <a href="<?php echo pxp_acp_link('manage-users?page-id=' . ($admin::$db->totalPages)); ?>" class="waves-effect" title='Last Page'>
                                                <i class="material-icons">last_page</i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- #END# Vertical Layout -->
<div id="delete-modal" class="modal fade" role="dialog" data-id="">
    <div class="modal-dialog">
        <div class="modal-content modal-col-red">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">DELETE USER</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to continue? this action can't be undo</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link waves-effect delete-button" data-dismiss="modal" data-type="user" data-id="">DELETE</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
</div>
<script>
$(function () {
	$(document).on('click', '.delete-content',function(event) {
        event.preventDefault();
        $('#delete-modal .delete-button').attr('data-id', $(this).attr('data-id')); 
		$('#delete-modal').attr('data-id', $(this).attr('data-id')).modal('show');
	});
});
</script>
