<?php if(!empty($context['user'])){ ?>

<tr id="list-<?php echo($cd['wal_requests']['id']); ?>" data-id="<?php echo($cd['wal_requests']['id']); ?>">
	<td>
		<input type="checkbox" id="check-list-<?php echo($cd['wal_requests']['id']);?>" class="item-checkbox filled-in">
		<label for="check-list-<?php echo($cd['wal_requests']['id']); ?>"></label>
	</td> 
	<td>
		<span>
			<?php echo($context['wal_requests']['id']) ?>
		</span>
	</td>
	<td>
		<span>
			<?php echo($context['user']['username']) ?>
		</span>
	</td>
	<td>
		<span>
			<?php echo($context['wal_requests']['account_number']) ?>
		</span>
	</td>
	<td>
		<span>
			<?php echo($context['wal_requests']['bank_name']) ?>
		</span>
	</td>
	<td>
		<address>
        <?php echo($context['user']['paypal_email']) ?>
		</address>
	</td>
	<td>
		<strong>
			<?php echo(Pxp_GetCurrency($context['wal_requests']['currency']).$context['wal_requests']['amount']) ?>
		</strong>
	</td>
	<td>
		<time>
			<?php echo ToDate($context['wal_requests']['requested']); ?>
		</time>
	</td>
	<td class="request-status">
		<?php if ($context['wal_requests']['status'] == 0): ?>
			<h3 class="m-t-5"><strong class="label label-warning">
				Pending
			</strong></h3>
		<?php elseif ($context['wal_requests']['status'] == 1):?>
			<h3 class="m-t-5"><strong class="label label-success">
				Paid
			</strong></h3>
		<?php elseif ($context['wal_requests']['status'] == 2):?>
			<h3 class="m-t-5"><strong class="label label-danger">
				Declined
			</strong></h3>
		<?php endif; ?>
		
	</td>
	<td>
      <button onclick="Pxp_ManageWRequests(<?php echo($context['wal_requests']['id']) ?>,1);" type="button" class="btn btn-info waves-effect waves-light"><i class="material-icons">check_circle</i></button>
    <?php if (!$context['wal_requests']['paid']) { ?>
      <button onclick="Pxp_ManageWRequests(<?php echo($context['wal_requests']['id']) ?>,4);" type="button" class="btn btn-success waves-effect waves-light pay_now">PAY NOW</button>
  	<?php } ?>
      <button onclick="Pxp_ManageWRequests(<?php echo($context['wal_requests']['id']) ?>,2);" type="button" class="btn btn-warning waves-effect waves-light">DECLINE</button>
      <button onclick="Pxp_ManageWRequests(<?php echo($context['wal_requests']['id']) ?>,3);" type="button" class="btn btn-danger waves-effect waves-light">DELETE</button>
   	</td>
</tr>
<?php } ?>
