<?php if(!empty($context['user'])){ ?>
<tr id="list-<?php echo($context['wal_requests']['id']) ?>">
	<td>
		<span>
			<?php echo($context['wal_requests']['id']) ?>
		</span>
	</td>
	<td>
		<span>
			<?php echo($context['user']['username']) ?>
		</span>
	</td>
	<td>
		<address>
        <?php echo($context['user']['paypal_email']) ?>
		</address>
	</td>
	<td>
		<strong>
			<?php echo(Pxp_GetCurrency($context['wal_requests']['currency']).$context['wal_requests']['amount']) ?>
		</strong>
	</td>
	<td>
		<time>
			<?php echo ToDate($context['wal_requests']['requested']); ?>
		</time>
	</td>
	<td class="request-status">
		<?php if ($context['wal_requests']['status'] == 0): ?>
			<span class="alert-warning">
				Pending
			</span>
		<?php elseif ($context['wal_requests']['status'] == 1):?>
			<span class="alert-success">
				Paid
			</span>
		<?php elseif ($context['wal_requests']['status'] == 2):?>
			<span class="alert-danger">
				Declined
			</span>
		<?php endif; ?>
		
	</td>
	<td>
      <button onclick="Pxp_ManageWRequests(<?php echo($context['wal_requests']['id']) ?>,1);" type="button" class="btn btn-success waves-effect waves-light">PAID</button>
      <button onclick="Pxp_ManageWRequests(<?php echo($context['wal_requests']['id']) ?>,2);" type="button" class="btn btn-warning waves-effect waves-light">DECLINE</button>
      <button onclick="Pxp_ManageWRequests(<?php echo($context['wal_requests']['id']) ?>,3);" type="button" class="btn btn-danger waves-effect waves-light">DELETE</button>
   	</td>
</tr>
<?php } ?>