<div class="block-header">
    <h2 class="breadcrumb">CHANGELOGS</h2>
</div>
     
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.3 <small>2019-12-9</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>[Added] store system, users can sell images. </li>
                    <li>[Added] blog system.</li>
                    <li>[Added] new APIs.</li>
                    <li>[Fixed] bugs</li>
                    <li>[Improved] speed.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.2.1 <small>2019-07-10</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>[Added] earnigns page in admin panel. </li>
                    <li>[Fixed] bugs</li>
                    <li>[Improved] speed.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.2 <small>2019-05-07</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>[Added] like comment system.</li>
                    <li>[Added] reply to comment system. </li>
                    <li>[Added] affiliate system. </li>
                    <li>[Added] more payment methods, bank transfer, stripe.</li>
                    <li>[Added] the ability to pause the story if you click on it.</li>
                    <li>[Added] To add money in the wallet from admin panel. </li>
                    <li>[Added] Ads system for users, users now can advertise on your site.</li>
                    <li>[Added] pro system, with new profile layout. </li>
                    <li>[Added] raise money system, photographers can ask for funding and get funded by users.</li>
                    <li>[Added] business account like Instagram.</li>
                    <li>[Added] follow requests, now if profile is private, it is required to accept a follow request before viewing the posts. </li>
                    <li>[Removed] @ from user profile url. </li>
                    <li>[Organized] Admin panel, added search for some pages, select all for posts, etc. </li>
                    <li>[Updated] Password hash system from sha1 to password_hash PHP function. </li>
                    <li>[Fixed] few important bugs.</li>
                    <li>[Improved] speed.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.1.2 <small>2019-01-13</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>[Fixed] few important bugs.</li>
                    <li>[Added] New API for the new native app.</li>
                    <li>[Improved] speed.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.1.1 <small>2018-11-21</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>[Fixed] few important bugs.</li>
                    <li>[Improved] speed.</li>
                </ul>
            </div>
        </div>
    </div>
     <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.1 <small>2018-10-29</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>[Added] face filters using webcam.</li>
                    <li>[Added] watermark system on images</li>
                    <li>[Added] support for mp4 links.</li>
                    <li>[Added] night mode</li>
                    <li>[Added] url fetcher, fetch images from urls.</li>
                    <li>[Added] blacklist system, for ip, username, emails.</li>
                    <li>[Added] lazyload for explore page (loads faster)</li>
                    <li>[Added] activities system (likes, comments, follow)</li>
                    <li>[Added] the abililty for the user to choose if their profile should be found/indexed.</li>
                    <li>[Added] ReCaptcha check to forgot password form</li>
                    <li>[Added] Session manager in settings page</li>
                    <li>[Added] Contact us page</li>
                    <li>[Added] emojis support for posts and comments.</li>
                    <li>[Added] Playtube support, you can import videos from a site that uses playtube script.</li>
                    <li>[Added] verification badge & system.</li>
                    <li>[Added] report filtration/warnings system.</li>
                    <li>[Added] startup page, upload avatar, fill info, follow.</li>
                    <li>[Added] emebd system, users can emebd posts from PixelPhoto using iframe.</li>
                    <li>[Added] video views system.</li>
                    <li>[Added] ajax load for pages (now pages load without refreshing).</li>
                    <li>[Added] full API system for the upcoming native app + docs.</li>
                    <li>[Fixed] few important bugs.</li>
                    <li>[Improved] speed.</li>
                </ul>
            </div>
        </div>
    </div>
     <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.0.3 <small>2018-08-13</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>Fixed few important bugs.</li>
                </ul>
            </div>
        </div>
    </div>
      <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.0.2 <small>2018-07-27</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>Fixed bugs in firefox and in video thumbnail.</li>
                </ul>
            </div>
        </div>
    </div>
     <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.0.1 <small>2018-07-26</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>Fixed bugs.</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>v1.0 <small>2018-07-20</small></h2>
            </div>
            <div class="body">
                <ul>
                    <li>First release.</li>
                </ul>
            </div>
        </div>
    </div>
</div>