<div class="container-fluid">
    <div class="block-header">
        <h2>Settings > Social Wallet Settings</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6"> 
            <div class="card">
                <div class="header">
                    <h2>Exclusive Plans / General Categories</h2>
                </div>
                <div class="body">
                    <form class="social-settings" method="POST">
                        <div class="form-alert"></div> 
                        <label for="exclusive_system">Exclusive System Status</label>
                        <div class="form-group">
                            <input type="radio" name="exclusive_system" id="exclusive_system-enabled" value="on" <?php echo ($config['exclusive_system'] == 'on') ? 'checked': '';?>>
                            <label for="exclusive_system-enabled">Enabled</label>
                            <input type="radio" name="exclusive_system" id="exclusive_system-disabled" value="off" <?php echo ($config['exclusive_system'] == 'off') ? 'checked': '';?>>
                            <label for="exclusive_system-disabled" class="m-l-20">Disabled</label>
                            <input type="radio" name="exclusive_system" id="exclusive_system-on_" value="on_" <?php echo ($config['exclusive_system'] == 'on_') ? 'checked': '';?>>
                            <label for="exclusive_system-on_" class="m-l-20">Hide Settings (Enabled)</label>
                        </div>

                        <label for="auto_pay_wallet">Auto Send Money</label>
                        <div class="form-group">
                            <input type="radio" name="auto_pay_wallet" id="auto_pay_wallet-enabled" value="on" <?php echo ($config['auto_pay_wallet'] == 'on') ? 'checked': '';?>>
                            <label for="auto_pay_wallet-enabled">Enabled</label>
                            <input type="radio" name="auto_pay_wallet" id="auto_pay_wallet-disabled" value="off" <?php echo ($config['auto_pay_wallet'] == 'off') ? 'checked': '';?>>
                            <label for="auto_pay_wallet-disabled" class="m-l-20">Disabled</label> 
                        </div>

                        <label for="auto_pay_wallet">Auto Send Money Limit</label>
                        <div class="form-group form-float">
                            <div class="form-line">
                                <input type="number" name="auto_pay_wallet_limit" class="form-control" value="<?php echo $config['auto_pay_wallet_limit'] ?>">
                                <label class="form-label">Limit</label>
                            </div>
                        </div> 
                        <button type="submit" class="btn btn-primary waves-effect">Save</button>
                        <hr>
                    </form>

                    <?php if ($config['exclusive_system'] == 'on'): ?>

                    <form class="wallet-settings" method="POST">
                        <div class="form-alert"></div> 

                        <?php $wallets = $admin->socialWallet(); $i = 0;
                            if (!empty($wallets)) { ?>
                                <?php foreach ($wallets as $key => $wallet) { $i++; ?> 
                                    <div id="wallet_<?php echo $wallet['id'] ?>" class="form_container">
                                        <label for="title">
                                            <?php echo $i . '. ' . $wallet['title'] ?> 
                                            <span class="black" data-toggle="popover" data-trigger="hover"><i class="fa fa-question-circle fa-fw"></i></span>
                                        </label>
                                        <button type="button" class="btn btn-danger" onclick="deleteSomething(<?php echo $wallet['id'] ?>,'wallet')">Delete</button><br>

                                        <input type="hidden" name="id[]" value="<?php echo $wallet['id'] ?>">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <input type="text" name="title[]" class="form-control" value="<?php echo $wallet['title'] ?>">
                                                <label class="form-label">Title</label>
                                            </div>
                                        </div>   
                                        <div class="row"> 
                                            <div class="col-md-4">
                                                <div class="form-group form-float">
                                                    <div class="form-line">
                                                        <input type="text" name="percentage[]" class="form-control" value="<?php echo $wallet['percentage'] ?>" max="100">
                                                        <label class="form-label">Percentage</label>
                                                    </div>
                                                </div>  
                                            </div>  
                                            <div class="col-md-4">
                                                <div class="form-group form-float">
                                                    <div class="form-line">
                                                        <input type="text" name="d_percentage[]" class="form-control" value="<?php echo $wallet['d_percentage'] ?>" max="100">
                                                        <label class="form-label">Donations Percentage</label>
                                                    </div>
                                                </div>  
                                            </div>    
                                            <div class="col-md-4">
                                                <div class="form-group form-float">
                                                    <select class="form-control show-tick" name="public[]">
                                                        <option value="1"<?php if ($wallet['public'] == 1) echo " selected" ?>>Public</option>
                                                        <option value="0"<?php if ($wallet['public'] == 0) echo " selected" ?>>Admin Only</option> 
                                                    </select>
                                                    <label class="form-label">Visibility</label>
                                                </div> 
                                            </div> 

                                            <input type="hidden" name="account_type[]" id="account_type<?php echo $i?>" value="">

                                            <div class="col-md-6">
                                                <div class="form-group form-float">
                                                    <select class="bank_code form-control show-tick" name="bank_code[]" id="bank_code<?php echo $i?>">
                                                        <?php echo $admin->bankOption($wallet['bank_code'])?>
                                                    </select>
                                                    <label class="form-label">Bank</label>
                                                </div> 
                                            </div> 

                                            <div class="col-md-6">
                                                <div class="form-group form-float">
                                                    <div class="form-line">
                                                        <input type="text" name="account_number[]" id="account_number<?php echo $i?>" class="form-control" value="<?php echo $wallet['account_number'] ?>">
                                                        <label class="form-label">Account Number</label>
                                                    </div>
                                                </div>  
                                            </div>   
                                        </div>  

                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <textarea class="form-control" name="description[]"><?php echo $wallet['description'] ?></textarea>
                                                <label class="form-label">Description</label>
                                            </div>
                                        </div> 
                                    </div>
                                <?php }?>

                                <br>  
                                <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                            <?php 
                            } else {
                                  echo $admin::createHtmlEl('div',array( 
                                    'class' => 'alert alert-warning',
                                ),"No wallet found");
                            }  
                        ?>
                    </form>
                                
                    <hr>
                    <form class="create-wallet" method="POST">
                        <div class="form-alert"></div>  
                        <div class="form-inline">
                            <label class="form-label">Title</label>
                            <input type="text" name="title" class="form-control" autocomplete="off">
                            <button type="submit" class="btn btn-primary btn-md waves-effect">Create New Plan</button>
                        </div> 
                    </form>
                    <?php endif;?>
                </div>
            </div>
        </div>
        
        <div class="col-lg-6 col-md-6">

        </div>
        <div class="clearfix"></div>
        
    </div>
</div>
    <!-- #END# Vertical Layout -->
<script>
    jQuery(document).ready(function($) {
        var proform = $("form.social-settings");
        proform.ajaxForm({
            url: acpajax_url('general-settings'),
            type: 'POST',
            dataType: 'json',
            beforeSubmit: function(arr,form){
                $(form).find('button[type=submit]').text('Please wait.').attr('disabled', 'true');
            },
            success: function(data, status, xhr, form){
                if (data.status == 200) {
                    $(form).find('div.form-alert').scroll2().html($('<div>',{
                        class:'alert alert-success',
                        text:'Settings has been updated successfully'
                    }));
                    setTimeout(function(){
                        proform.find('div.form-alert .alert').slideUp('fast',function(){
                            $(this).remove(); 
                        })    
                    },1000);
                }
                else{
                    $(form).find('div.form-alert').scroll2().html($('<div>',{
                        class:'alert alert-warning',
                        text: data.error
                    }));
                }

                proform.find('button[type=submit]').text('Save').removeAttr('disabled');
            }
        });
        
        var communityForm = $("form.wallet-settings");
        communityForm.ajaxForm({
            url: acpajax_url('wallet-settings'),
            type: 'POST',
            dataType: 'json',
            beforeSubmit: function(arr,form){
                $(form).find('button[type=submit]').text('Please wait.').attr('disabled', 'true');
            },
            success: function(data, status, xhr, form){
                if (data.status == 200) {
                    $(form).find('div.form-alert').scroll2().html($('<div>',{
                        class:'alert alert-success',
                        text:'Settings has been updated successfully'
                    }));
                    setTimeout(function(){
                        communityForm.find('div.form-alert .alert').slideUp('fast',function(){
                            $(this).remove(); 
                        })    
                    },1000);
                }
                else{
                    $(form).find('div.form-alert').scroll2().html($('<div>',{
                        class:'alert alert-warning',
                        text: data.error
                    }));
                }

                communityForm.find('button[type=submit]').text('Save').removeAttr('disabled');
            }
        });
         
        var cexclusiveForm = $("form.create-wallet");
        cexclusiveForm.ajaxForm({
            url: acpajax_url('create-wallet'),
            type: 'POST',
            dataType: 'json',
            beforeSubmit: function(arr,form){
                $(form).find('button[type=submit]').text('Please wait.').attr('disabled', 'true');
            },
            success: function(data, status, xhr, form){
                if (data.status == 200) {
                    location.reload(true);
                }
                else{
                    $(form).find('div.form-alert').scroll2().html($('<div>',{
                        class:'alert alert-warning',
                        text: data.error
                    }));
                }

                cexclusiveForm.find('button[type=submit]').text('Create Wallet').removeAttr('disabled');
            }
        });
        $(".bank_code").each(function(e, group){
            var posn = (e+1);
            $("select#bank_code"+posn).change(function(event) {
                var account_number = $('#account_number'+posn).val(); 
                var selected       = $(this).children("option:selected"); 
                $('#account_type'+posn).val(selected.data('type'));

                console.log(selected.text());
                console.log(selected.data('type'));
                console.log(selected.val());
                console.log(account_number);
            }); 
            $("#account_number"+posn).keydown(function(event) { 
                var account_number = $(this).val(); 
                var bank_code      = $("select#bank_code"+posn).children("option:selected").val(); 
                if (account_number.length >= 7) {
                    checkAccountNumber(event, account_number, bank_code, div_id = '');
                }
            }); 
        }); 
    });
    
    function checkAccountNumber(e, account_number, bank_code, div_id = '') {
        charStr = String.fromCharCode(e.keyCode);
        if (/[0-9-_]/.test(charStr)) {
            // $.post(link('main/verify_account_number'), 
            //     {account_number:account_number,bank_code:selected.val()}, 
            //     function(data, textStatus, xhr) {

            // });
            console.log('Checking Account Number'); 
            console.log(account_number.length, account_number, bank_code);
        } 
    }
         
    function deleteSomething(id,what) {
        $.post(
            acpajax_url('delete-'+what), 
            {id:id,what:what}, 
            function(data, textStatus, xhr) {console.log(what)
                if (data.status == 200) {
                    $('#'+what+'_'+id).slideUp();
                }
                else{
                    $('form.'+what+'-settings').find('div.form-alert').scroll2().html($('<div>',{
                        class:'alert alert-warning',
                        text: data.error
                    }));
                } 
            }
        );  
    }
</script>
