<?php 
$terms = $admin->getPage('terms_of_use');
$post_id = (!empty($_GET['post_id'])) ? $admin::secure($_GET['post_id']) : '';
$query   = (!empty($_GET['query'])) ? $admin::secure($_GET['query']) : '';

$all_content =  $admin->noticeModalContent($query, true);
$content     =  $admin->noticeModalContent($post_id);
$status      = (!empty($content['status']) ? $content['status'] : 'on');
$content_id  = (!empty($content['id']) ? $content['id'] : '');
?>

<div class="block-header">
    <h2 class="breadcrumb">Pages <i class="material-icons">keyboard_arrow_right</i> Notice Modal Content</h2>
</div>
<div class="row clearfix">
    <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Write Terms of use of this website</h2>
            </div>
            <div class="body">
                <div class="clearfix">
                    <form class="form info-modal-form">
                    	<div class="form-alert"></div>
                        <input type="hidden" id="id" name="id" value="<?php echo $content_id; ?>">
                        <div class="form-group"> 
                            <div class="form-line">
                                <label class="form-label">Content Title</label> 
                                <input type="text" id="title" name="title" class="form-control" value="<?php echo (!empty($content['title']) ? $content['title'] : ''); ?>" required>
                            </div>
                        </div>
                        <div class="form-group"> 
                            <div class="form-line">
                                <label class="form-label">Pages Allowed (Comma Separated, titles or id's)</label> 
                                <input type="text" id="in_pages" name="in_pages" class="form-control" value="<?php echo (!empty($content['in_pages']) ? $content['in_pages'] : ''); ?>">
                            </div>
                        </div>

                        <label for="upload_system">Status</label>
                        <div class="form-group">
                            <input type="radio" name="status"  value="on" id="status-enabled" <?php echo ($status == 'on') ? 'checked': '';?>>
                            <label for="status-enabled">Active</label>
                            <input type="radio" name="status" id="status-disabled" value="off" <?php echo ($status == 'off') ? 'checked': '';?>>
                            <label for="status-disabled" class="m-l-20">Inactive</label>
                        </div>
						<div class="form-group">
							<textarea name="content" id="content"><?php echo (!empty($content['content']) ? $content['content'] : ''); ?></textarea>
						</div>
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>Manage Content</h2>
            </div>
            <div class="body">
                <div class="table-alert"></div>
                <div class="table-responsive1">
                    <table class="table table-bordered table-striped table-hover table-users">
                        <thead>
                            <tr> 
                                <th>ID</th>
                                <th>Title</th> 
                                <th>Status</th> 
                            </tr>
                        </thead>
                        <tbody id="sortable">
                        <?php
                            if (!empty($all_content)) {
                                foreach ($all_content as $key => $context['content']) { 
                                    echo $admin->loadPage('modal/list');
                                }
                            }
                            else{
                                echo $admin::createHtmlEl('tr',null,$admin::createHtmlEl('td',array(
                                    'colspan' => 3,
                                    'class' => 'empty-table',
                                ),"No Info Modal content found"));
                            }  
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>    
</div>
<script src="<?php echo pxp_acp_link('plugins/tinymce/tinymce.js');?>"></script>
<script>
    jQuery(document).ready(function($) {
        tinymce.init({
            selector: '#content',
            relative_urls: false,
            remove_script_host: false,
            height:500,
            toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link | preview fullpage | forecolor backcolor emoticons',
            plugins: [
                'advlist autolink link  lists charmap  preview hr anchor spellchecker',
                'searchreplace wordcount visualblocks visualchars code fullscreen insertdatetime media nonbreaking',
                'save table contextmenu directionality emoticons template paste textcolor'
            ]
        });

        var info_modal_form = $("form.info-modal-form");

        info_modal_form.submit(function(event) {
            var text = tinymce.activeEditor.getContent({format: 'raw'});
            if (!text){
                info_modal_form.find('div.form-alert').scroll2().html($('<div>',{
                    class:'alert alert-danger',
                    text:'Can not save changes, something went wrong Please try again'
                }));

                setTimeout(function(){
                    window.location.reload();
                });

                return false;
            }
            else{
                $("#content").val(text);
            }   
        });

        info_modal_form.ajaxForm({
            url: acpajax_url('info-modal'),
            type: 'POST',
            dataType: 'json',
            beforeSubmit: function(arr,form){
                arr[4]['value'] = btoa(unescape(encodeURIComponent(arr[4]['value'])));
                $(form).find('button[type=submit]').text('Please wait.').attr('disabled', 'true');
            },
            success: function(data, status, xhr, form){
                var set_id = $(form).find('#id').val();
                if (data.status == 200) {
                    $(form).find('#id').val((set_id ? set_id : (data.sid ? data.sid : '')));
                    $(form).find('div.form-alert').scroll2().html($('<div>',{
                        class: 'alert alert-success',
                        text: data.message
                    }));
                    setTimeout(function(){
                        info_modal_form.find('div.form-alert .alert').slideUp('fast',function(){
                            $(this).remove(); 
                        })    
                    },3000);console.log(set_id);
                }
                else{
                    $(form).find('div.form-alert').scroll2().html($('<div>',{
                        class: 'alert alert-warning',
                        text: data.message
                    }));
                }
                
                info_modal_form.find('button[type=submit]').text('Save').removeAttr('disabled');
            }
        });

        $(document).on('click', '.delete-content',function(event) {
            event.preventDefault();

            var id        = $(this).attr('data-id');
            var action    = 'delete'; 

            $(this).text('Please wait.').attr('disabled', 'true');
            $.post(acpajax_url('info-modal'), {id:id,action:action}, function (data) {
                $('.delete-content').text('DELETE').removeAttr('disabled');
                if (data.status == 200) {
                    $('#list-'+id).fadeOut();
                    location.reload(true);
                }
                $('div.table-alert').scroll2().html($('<div>',{
                    class: 'alert alert-'+(data.status == 200 ? 'success' : 'warning'),
                    text: data.message
                }));
            });
        });
    });
    
    // jQuery UI sortable for the todo list 
    $('#sortable').sortable({
        placeholder          : 'sort-highlight',
        handle               : '.handle',
        forcePlaceholderSize : true,
        zIndex               : 999999,
        update: function (event, ui) {
            var sort_order = $(this).sortable('serialize');
            $.ajax({
                async: true,
                type: 'POST',
                url: acpajax_url('sort-info-modal'),
                data: sort_order,  
                dataType: 'JSON',
                success: function(resps) { 
                    console.log(resps);
                },
                error: function(xhr, status, error) { 
                    console.log(xhr, xhr.responseText);
                }  
            })
        }
    }) 
</script>
