<?php 
$terms = $admin->getPage('terms_of_use');
$post_id = (!empty($_GET['post_id'])) ? $admin::secure($_GET['post_id']) : '';
$query   = (!empty($_GET['query'])) ? $admin::secure($_GET['query']) : '';

$all_content =  $admin->noticeModalContent($query, true);
$content     =  $admin->noticeModalContent($post_id);
$status      = (!empty($content['status']) ? $content['status'] : 'on');
$use_title   = (!empty($content['use_title']) ? $content['use_title'] : 'on');
$content_id  = (!empty($content['id']) ? $content['id'] : '');
?>

<div class="block-header">
    <h2 class="breadcrumb">Pages <i class="material-icons">keyboard_arrow_right</i> Notice Modal Content</h2>
</div>
<div class="row clearfix"> 
    <div class="col-lg-3 col-md-3 p-b-5">
        <button class="btn btn-info btn-lg" onclick="location.href='<?php echo(pxp_acp_link('modal-writer')); ?>'">Add new content</button>
    </div>
    <div class="col-md-12">
        <div class="card">
            <div class="header"> 
                <h2>Manage Manifest and Info Board</h2>
            </div> 
            <div class="body">
                <small class="text-info">Drag Handle to reposition</small>
                <div class="table-alert"></div>
                <div class="table-responsive1">
                    <table class="table table-bordered table-striped table-hover table-users">
                        <thead>
                            <tr> 
                                <th>ID</th>
                                <th>Title</th> 
                                <th>Status</th> 
                            </tr>
                        </thead>
                        <tbody id="sortable">
                        <?php
                            if (!empty($all_content)) {
                                foreach ($all_content as $key => $context['content']) { 
                                    echo $admin->loadPage('modal/list');
                                }
                            }
                            else{
                                echo $admin::createHtmlEl('tr',null,$admin::createHtmlEl('td',array(
                                    'colspan' => 3,
                                    'class' => 'empty-table',
                                ),"No Info Modal content found"));
                            }  
                        ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>    
</div>
<script src="<?php echo pxp_acp_link('plugins/tinymce/tinymce.js');?>"></script>
<script>
    jQuery(document).ready(function($) { 
        $(document).on('click', '.delete-content',function(event) {
            event.preventDefault();

            var id        = $(this).attr('data-id');
            var action    = 'delete'; 

            $(this).text('Please wait.').attr('disabled', 'true');
            $.post(acpajax_url('info-modal'), {id:id,action:action}, function (data) {
                $('.delete-content').text('DELETE').removeAttr('disabled');
                if (data.status == 200) {
                    $('#list-'+id).fadeOut();
                    location.reload(true);
                }
                $('div.table-alert').scroll2().html($('<div>',{
                    class: 'alert alert-'+(data.status == 200 ? 'success' : 'warning'),
                    text: data.message
                }));
            });
        });
    });
    
    // jQuery UI sortable for the todo list 
    $('#sortable').sortable({
        placeholder          : 'sort-highlight',
        handle               : '.handle',
        forcePlaceholderSize : true,
        zIndex               : 999999,
        update: function (event, ui) {
            var sort_order = $(this).sortable('serialize');
            var _i = $(event.toElement).next('i');
            _i.text(' wait...').show(); 
            $.ajax({
                async: true,
                type: 'POST',
                url: acpajax_url('sort-info-modal'),
                data: sort_order,  
                dataType: 'JSON',
                success: function(resps) { 
                    console.log(resps);
                    _i.hide(); 
                },
                error: function(xhr, status, error) { 
                    console.log(xhr, xhr.responseText);
                }  
            })
        }
    }) 
</script>
