<tr id="list-<?php echo($cd['content']['id']); ?>" data-id="<?php echo($cd['content']['id']); ?>"> 
	<td>
		<span>
			<?php echo($cd['content']['id']); ?>
		</span>
		<span  class="handle material-icons" style="cursor: move;">swap_vert</span>
	</td> 
	<td>
		<span>
			<a href="<?php echo(pxp_acp_link('modal?post_id='.$cd['content']['id'])); ?>">
				<?php echo($cd['content']['title'] ?? 'Removed Challenge'); ?>
			</a> 
		</span>
	</td>
	<td>
		<span>
			<?php echo($cd['content']['status'] == 'on' ? 'Active' : 'Inactive'); ?>
		</span>
		<br>
		<button class="btn btn-danger waves-effect waves-light delete-content" data-id="<?php echo($cd['content']['id']);?>">
			DELETE
		</button>
	</td> 
</tr>
