<?php 
$fb_login_on  = ($config['fb_login'] == 'on') ? 'checked' : '';
$fb_login_off = ($config['fb_login'] == 'off') ? 'checked' : '';

$tw_login_on  = ($config['tw_login'] == 'on') ? 'checked' : '';
$tw_login_off = ($config['tw_login'] == 'off') ? 'checked' : '';

$gl_login_on  = ($config['gl_login'] == 'on') ? 'checked' : '';
$gl_login_off = ($config['gl_login'] == 'off') ? 'checked' : '';

$wowonder_login_on  = ($config['wowonder_login'] == 'on') ? 'checked' : '';
$wowonder_login_off = ($config['wowonder_login'] == 'off') ? 'checked' : '';
?>

<div class="block-header">
    <h2 class="breadcrumb">Settings <i class="material-icons">keyboard_arrow_right</i> Social Login Settings</h2>
</div>
<div class="row">
    <div class="col-lg-3 col-md-3">
        <div class="card">
            <div class="header">
                <h2>Social Login Settings</h2>
            </div>
            <div class="body">    
                <form class="form login-settings-form" method="POST">
                    <div class="form-alert"></div>
                    <label for="fb_login">Facebook</label>
                    <div class="form-group">
                        <input type="radio" name="fb_login" id="fb_login-enabled" value="on" <?php echo($fb_login_on); ?>>
                        <label for="fb_login-enabled">Enabled</label>
                        <input type="radio" name="fb_login" id="fb_login-disabled" value="off" <?php echo($fb_login_off); ?>>
                        <label for="fb_login-disabled" class="m-l-20">Disabled</label>
                    </div>
                    <label for="tw_login">Twitter</label>
                    <div class="form-group">
                        <input type="radio" name="tw_login" id="tw_login-enabled" value="on" <?php echo($tw_login_on); ?>>
                        <label for="tw_login-enabled">Enabled</label>
                        <input type="radio" name="tw_login" id="tw_login-disabled" value="off" <?php echo($tw_login_off); ?>>
                        <label for="tw_login-disabled" class="m-l-20">Disabled</label>
                    </div>
                    <label for="gl_login">Google+</label>
                    <div class="form-group">
                        <input type="radio" name="gl_login" id="gl_login-enabled" value="on" <?php echo $gl_login_on; ?>>
                        <label for="gl_login-enabled">Enabled</label>
                        <input type="radio" name="gl_login" id="gl_login-disabled" value="off" <?php echo($gl_login_off); ?>>
                        <label for="gl_login-disabled" class="m-l-20">Disabled</label>
                    </div>
                    <label for="wowonder_login">WoWonder (Your Own Site) <a href="#" data-toggle="modal" data-target="#wowonder">?</a></label>
                    <div class="form-group">
                        <input type="radio" name="wowonder_login" id="wowonder_login-enabled" value="on" <?php echo($wowonder_login_on);?>>
                        <label for="wowonder_login-enabled">Enabled</label>
                        <input type="radio" name="wowonder_login" id="wowonder_login-disabled" value="off" <?php echo($wowonder_login_off);?>>
                        <label for="wowonder_login-disabled" class="m-l-20">Disabled</label>
                    </div>
                    <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-9 col-md-9">
        <div class="card">
            <div class="header">
                <h2>API Keys</h2>
            </div>
            <div class="body">
                <form class="form login-settings-form" method="POST">
                    <div class="form-alert"></div>
                    <div class="form-group form-float">
                        <div class="form-line focused">
                            <input type="text" id="facebook_app_id" name="facebook_app_id" class="form-control" value="<?php echo($config['facebook_app_id']); ?>">
                            <label class="form-label">Facebook API ID</label>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <div class="form-line focused">
                            <input type="text" id="facebook_app_key" name="facebook_app_key" class="form-control" value="<?php echo($config['facebook_app_key']); ?>">
                            <label class="form-label">Facebook API Key</label>
                        </div>
                    </div>
                    <br>
                    <div class="form-group form-float">
                        <div class="form-line focused">
                            <input type="text" id="twitter_app_id" name="twitter_app_id" class="form-control" value="<?php echo($config['twitter_app_id']); ?>">
                            <label class="form-label">Twitter API ID</label>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <div class="form-line focused">
                            <input type="text" id="twitter_app_key" name="twitter_app_key" class="form-control" value="<?php echo($config['twitter_app_key']); ?>">
                            <label class="form-label">Twitter API Key</label>
                        </div>
                    </div>
                    <br>
                    <div class="form-group form-float">
                        <div class="form-line focused">
                            <input type="text" id="google_app_id" name="google_app_id" class="form-control" value="<?php echo($config['google_app_id']); ?>">
                            <label class="form-label">Google API ID</label>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <div class="form-line focused">
                            <input type="text" id="google_app_key" name="google_app_key" class="form-control" value="<?php echo($config['google_app_key']); ?>">
                            <label class="form-label">Google API Key</label>
                        </div>
                    </div>
                    <br>
                    <div class="form-group form-float">
                        <div class="form-line">
                            <input type="text" id="wowonder_app_ID" name="wowonder_app_ID" class="form-control" value="<?php echo($config['wowonder_app_ID']); ?>">
                            <label class="form-label">WoWonder API Key</label>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <div class="form-line">
                            <input type="text" id="wowonder_app_key" name="wowonder_app_key" class="form-control" value="<?php echo($config['wowonder_app_key']); ?>">
                            <label class="form-label">WoWonder API Secret</label>
                        </div>
                    </div>
                    <div class="form-group form-float">
                        <div class="form-line">
                            <input type="text" id="wowonder_domain_uri" name="wowonder_domain_uri" class="form-control" value="<?php echo($config['wowonder_domain_uri']); ?>">
                            <label class="form-label">WoWonder Domain <small>The domain of your website that uses WoWonder Social Network</small></label>
                        </div>
                    </div>
                    <div class="form-group form-float">
                            <div class="form-line">
                                <input type="text" id="wowonder_domain_icon" name="wowonder_domain_icon" class="form-control" value="<?php echo($config['wowonder_domain_icon']); ?>">
                                <label class="form-label">WoWonder Icon <small>Link to your icon, example: <a href="https://demo.wowonder.com/themes/default/img/icon.png">https://demo.wowonder.com/themes/default/img/icon.png</a></small></label>
                            </div>
                        </div>
                    <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                </form>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<div id="wowonder" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">WoWonder Integration</h4>
      </div>
      <div class="modal-body">
        <p>This feature allows you to integrate users from your own website that uses <a href="http://www.wowonder.com" target="_blank">WoWonder</a>.</p>
        <p>To get started please follow those steps:</p>
        <ul>
            <li>Go to http://yoursite.com/developers, you'll get the following <a target="_blank" href="<?php echo pxp_acp_link('images/Screenshot_1.png'); ?>">Page</a></li>
            <li>Click on "Create an app", and fill the required information.</li>
            <li>On the form, make sure the info are similar as shown <a target="_blank" href="<?php echo pxp_acp_link('images/Screenshot_2.png'); ?>">Here</a>.</li>
            <li>Save the form, get the <a  target="_blank" href="<?php echo pxp_acp_link('images/Screenshot_4.png'); ?>">Keys</a>, and use them <a target="_blank" href="<?php echo pxp_acp_link('images/Screenshot_3.png'); ?>">Here</a>.</li>
        </ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<script>
    jQuery(document).ready(function($) {
        var slform = $("form.login-settings-form");

        slform.ajaxForm({
            url: acpajax_url('login-settings'),
            type: 'POST',
            dataType: 'json',
            beforeSubmit: function(arr,form){
                $(form).find('button[type=submit]').text('Please wait.').attr('disabled', 'true');
            },
            success: function(data, status, xhr, form){
                if (data.status == 200) {
                    $(form).find('div.form-alert').scroll2().html($('<div>',{
                        class:'alert alert-success',
                        text:'Settings has been updated successfully'
                    }));
                    setTimeout(function(){
                        slform.find('div.form-alert .alert').slideUp('fast',function(){
                            $(this).remove(); 
                        })    
                    },1000);
                }
                else{
                    $(form).find('div.form-alert').scroll2().html($('<div>',{
                        class:'alert alert-warning',
                        text: data.error
                    }));
                }

                slform.find('button[type=submit]').text('Save').removeAttr('disabled');
            }
        });
    });
</script>