<?php
$page = (!empty($_GET['page-id'])) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? $admin::secure($_GET['query']) : '';
$filter_type    = '';
$admin::$db->pageLimit = 50;
if (!empty($filter_keyword)) {

    if (is_numeric($filter_keyword)) {
        $admin::$db->where('`id`',"$filter_keyword");
    } else {
        $admin::$db->where('`title`',"%$filter_keyword%",'LIKE');
    }

    $posts = $admin::$db->orderBy('id', 'DESC')->paginate(T_STORE, $page,array('*'));
}

else {
    $posts = $admin::$db->orderBy('id', 'DESC')->paginate(T_STORE, $page,array('*'));
}

if (($page > $admin::$db->totalPages) && !empty($_GET['page-id'])) {
    header("Location: " . pxp_acp_link('manage-store-items'));
    exit();
}

?>
<div class="container-fluid">
    <div class="block-header">
        <h2>Image Store > Manage store items</h2>
    </div>
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="body">
                   <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Owner</th>
                                    <th>Title</th>
                                    <th>Tags</th>
                                    <th>Views</th>
                                    <th>Downloads</th>
                                    <th>Sales</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                            <?php
                            foreach ($posts as $key => $wo['item']) {
                                $context['item'] = o2array($wo['item']);
                                $user = $admin::$db->where('user_id',$context['item']['user_id'])->getOne(T_USERS);
                                $context['item']['user'] = o2array($admin->userData($user));
                                echo $admin->loadPage('manage-store-items/list');
                            }
                            ?>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- #END# Vertical Layout -->
<script>
    $('.btn-lang').on('click', function(event) {
        $('#defaultModal .modal-body form .data').html('<div class="preloader pl-size-xl "><div class="spinner-layer pl-teal"><div class="circle-clipper left"><div class="circle"></div></div><div class="circle-clipper right"><div class="circle"></div></div></div></div>');
        var lang_id = $(this).attr('data-id');
        $.get(acpajax_url('get_lang_key'), {id: lang_id, lang_name: lang_id}, function(data, textStatus, xhr) {
            $('#defaultModal .modal-title').html('Edit key: ' + lang_id);
            $('#id_of_key').val(lang_id);
            $('#defaultModal .modal-body form .data').html(data.html);
        });
    });
    function Wo_SubmitLangForm() {
        $('.edit-key-settings').submit();
    }
    function Wo_SubmitAddCategoryForm() {
        $('.langsModalForm').submit();
    }
    $(function () {
        $('table').DataTable();
        var form_lang_settings = $('form.edit-key-settings');
        form_lang_settings.ajaxForm({
            url: acpajax_url('update_lang_key'),
            beforeSend: function() {
                $('.btn-save').text('Please wait..');
            },
            success: function(data) {
                if (data.status == 200) {
                    $('.btn-save').text('SAVE CHANGES');
                    var value_to_use = $('[data-editable=1]').val();
                    var id_of_key = $('#id_of_key').val();
                    $('#edit_' + id_of_key).text(value_to_use);
                    $('#defaultModal').modal('hide');
                    location.reload();
                }
            }
        });

        var form_gender_settings = $('form.langsModalForm');
        form_gender_settings.ajaxForm({
            url: acpajax_url('add_new_store_category'),
            beforeSend: function() {
                $('.btn-save').text('Please wait..');
            },
            success: function(data) {

                if (data.status == 200) {
                    $('.btn-save').text('SAVE CHANGES');
                    $('#langsModal').modal('hide');
                    location.reload();
                }
                else{
                    $('.btn-save').text('SAVE CHANGES');
                    $('.langsModalAlert').html(data.message);
                }
                $("#langsModal").animate({ scrollTop: 0 }, 100);

            }
        });
    });

    $(document).on('click', '#add_new_category', function(event) {
        $('#langsModal').modal('show');
        $("#langsModal").on('shown.bs.modal', function(){
            $(this).find('textarea[name="english"]').focus();
        });
    });
    function Wo_DeleteStoreItem(key) {
        if (key == '') {
            return false;
        }
        if (!confirm('Are you sure you want to delete this category?')) {
            return false;
        }

        $.get(acpajax_url('delete_store_item'), {key:key}, function (data) {
            if(data.status == 300){
                alert('You can not delete this record.');
            }else{
                $('#' + key).fadeOut(300, function () {
                    $(this).remove();
                });
            }
        });
    }
</script>
<div class="modal fade" id="defaultModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content ">
            <div class="modal-header">
                <h4 class="modal-title" id="defaultModalLabel"></h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-success edit-lang-settings-alert" style="display:none;"></div>
                <form class="edit-key-settings" method="POST">
                    <div class="data"></div>
                    <input type="hidden" name="id_of_key" id="id_of_key" value="">
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="Wo_SubmitLangForm();" class="btn-save btn btn-link waves-effect">SAVE CHANGES</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="langsModal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content ">
            <div class="modal-header">
                <h4 class="modal-title" id="langsModalLabel"></h4>
            </div>
            <div class="modal-body">
                <div class="alert alert-danger langsModalAlert" style="display:none;"></div>
                <form class="langsModalForm" method="POST">
                    <?php foreach (LangsNamesFromDB() as $wo['key_']) { ?>
                        <div class="form-group">
                            <div class="form-lins">
                                <label class="form-lasbel"><?php echo ucfirst($wo['key_']); ?></label>
                                <textarea style="resize: none;" name="<?php echo $wo['key_']; ?>" id="<?php echo $wo['key_']; ?>" class="form-control" cols="20" rows="2"></textarea>
                            </div>
                        </div>
                    <?php } ?>
                    <div class="data"></div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" onclick="Wo_SubmitAddCategoryForm();" class="btn-save btn btn-link waves-effect">SAVE CHANGES</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
</div>