<tr id="<?php  echo $cd['item']['id'];?>">
    <td><?php  echo $cd['item']['id'];?></td>
    <td>
        <a href="<?php echo $config['site_url'] . '/@' . $cd['item']['user']['username']; ?>" target="_blank">
            <img src="<?php echo $cd['item']['user']['avatar'];?>" class="setting-avatar" alt="<?php echo $cd['item']['user']['username'];?> Profile Picture">
            <?php echo $cd['item']['user']['name']; ?>
        </a>
        <br>
        <span style="color:#607D8B;font-size: 11px;font-weight: bold;" class=" ajax-time" title="<?php echo date('c', $cd['item']['created_date']); ?>"><?php echo(time2str($cd['item']['created_date'])); ?></span>

    </td>
    <td id="edit_<?php echo $cd['item']['id'];?>">
        <a href="<?php echo $config['site_url'] . '/store/' . $cd['item']['id']; ?>" target="_blank">
            <img src="<?php echo media($cd['item']['small_file']);?>" class="setting-avatar" alt="<?php echo $cd['item']['title'];?>">
            <?php echo $cd['item']['title'];?>
        </a>
        <br>
        <span style="color:#607D8B;font-size: 11px;font-weight: bold;">Price : <?php echo  $config['currency'] .' '.$cd['item']['price']; ?></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <span style="color:#607D8B;font-size: 11px;font-weight: bold;">Category : <?php echo lang($cd['item']['category']); ?></span>
    </td>
    <td><?php  echo $cd['item']['tags'];?></td>
    <td><?php  echo $cd['item']['views'];?></td>
    <td><?php  echo $cd['item']['downloads'];?></td>
    <td><?php  echo $cd['item']['sells'];?></td>
    <td>
<!--        <button type="button" class="btn btn-default waves-effect btn-lang m-r-20" data-id="--><?php //echo $cd['item']['id'];?><!--" data-toggle="modal" data-target="#defaultModal">EDIT</button>-->
        <button onclick="Wo_DeleteStoreItem('<?php echo $cd['item']['id'];?>');" type="button" class="btn btn-danger waves-effect waves-light">DELETE</button>
    </td>
</tr>