<?php 
define('T_CONFIG', 'pxp_config');
define('T_LANGS', 'pxp_langs');
define('T_SESSIONS', 'pxp_sessions');
define('T_USERS', 'pxp_users');
define('T_MEDIA', 'pxp_media_files');
define('T_POSTS', 'pxp_posts');
define('T_POST_COMMENTS', 'pxp_post_comments');
define('T_CONNECTIV', 'pxp_connectivities');
define('T_MESSAGES', 'pxp_messages');
define('T_STORY', 'pxp_story');
define('T_STORY_VIEWS', 'pxp_story_views');
define('T_NOTIF', 'pxp_notifications');
define('T_POST_LIKES', 'pxp_post_likes');
define('T_CHATS', 'pxp_chats');
define('T_SAVED_POSTS', 'pxp_saved_posts');
define('T_POST_REPORTS','pxp_post_reports');
define('T_USER_REPORTS','pxp_user_reports');
define('T_PROF_BLOCKS','pxp_blocks');
define('T_HTAGS','pxp_hashtags');
define('T_STAT_PAGES','pxp_static_pages');
define('T_VERIFY','pxp_verification_requests');
define('T_BLACKLIST','pxp_blacklist');
define('T_ACTIVITIES','pxp_activities');
define('T_COMMENTS_LIKES','pxp_comments_likes');
define('T_COMMENTS_REPLY','pxp_comments_reply');
define('T_COMMENTS_REPLY_LIKES','pxp_comments_reply_likes');
define('T_BANK_TRANSFER', 'pxp_bank_receipts');
define('T_PAYMENTS', 'pxp_payments');
define('T_ADS', 'pxp_userads');
define('T_WITHDRAWAL', 'pxp_withdrawal_requests');
define('T_FUNDING', 'pxp_funding');
define('T_FUNDING_RAISE', 'pxp_funding_raise');
define('T_BUS_REQUESTS', 'pxp_business_requests');
define('T_TRANSACTIONS', 'pxp_transactions');
define('T_BLOG', 'pxp_blog');
define('T_STORE', 'pxp_store');
define('T_CHALLENGE', 'pxp_challenges');
define('T_MODAL', 'pxp_info_modal');
define('T_COMMUNITY', 'pxp_community_accounts');
