<?php
$page           = (!empty($_GET['page-id']) && is_numeric($_GET['page-id'])) ? $admin::secure($_GET['page-id']) : 1;
$filter_keyword = (!empty($_GET['query'])) ? $admin::secure($_GET['query']) : '';
$admin::$db->pageLimit  = 20;

if(isset($_GET['approved'])){
    $admin::$db->where('approved',1);
}else{
    $admin::$db->where('approved',0);
}

if (!empty($filter_keyword)) {
    $approved = 0;
    if(isset($_GET['approved'])){
        $approved = 1;
    }

    $mediafiles = $admin::$db->rawQuery("SELECT * FROM  " . T_BANK_TRANSFER . " 
      WHERE `user_id` IN (SELECT `user_id` FROM " . T_USERS . " WHERE `username` LIKE '%$filter_keyword%' OR `email` LIKE '%$filter_keyword%' OR `fname` LIKE '%$filter_keyword%' OR `lname` LIKE '%$filter_keyword%' OR `user_id` LIKE '%$filter_keyword%') AND `approved` = '$approved'");
}

else {
    $mediafiles = $admin::$db->objectbuilder()->orderBy('approved_at', 'DESC')->orderBy('id', 'DESC')->paginate(T_BANK_TRANSFER, $page);
}

if (($page > $admin::$db->totalPages) && !empty($_GET['page-id'])) {
    header("Location: " . pxp_acp_link('bank-receipts'));
    exit();
}

$approved_count = $admin::$db->where('approved',1)->getValue(T_BANK_TRANSFER,'count(id)');
$disapproved_count = $admin::$db->where('approved',0)->getValue(T_BANK_TRANSFER,'count(id)');
?>
<div class="container-fluid">
    <div class="block-header">
        <h2>Earnings > Manage bank receipts</h2>
    </div>

    <div class="row clearfix">
        <div class="col-lg-3 col-md-3">
            <a href="<?php echo pxp_acp_link('bank-receipts');?>?approved=true">
            <div class="info-box bg-light-green hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">check</i>
                </div>
                <div class="content">
                    <div class="text">Approved</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo $approved_count; ?>" data-speed="15" data-fresh-interval="20"><?php echo $approved_count; ?></div>
                </div>
            </div>
            </a>
        </div>
        <div class="col-lg-3 col-md-3 ">
            <a href="<?php echo pxp_acp_link('bank-receipts');?>">
            <div class="info-box bg-red hover-expand-effect">
                <div class="icon">
                    <i class="material-icons">clear</i>
                </div>
                <div class="content">
                    <div class="text">Disapproved</div>
                    <div class="number count-to" data-from="0" data-to="<?php echo $disapproved_count; ?>" data-speed="1000" data-fresh-interval="20"><?php echo $disapproved_count; ?></div>
                </div>
            </div>
            </a>
        </div>

    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage bank receipts</h2>
                </div>
                <br>
                <div class="clearfix">
                        <div class="col-md-6" style="margin-bottom:0;">
                            <form method="get" action="<?php echo pxp_acp_link('bank-receipts'); ?>">
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <input type="text" name="query" id="query" class="form-control"  value="<?php echo($filter_keyword); ?>">
                                                <label class="form-label search-form">Search for ID, Keyword, E-mail, Username, First Name, Last Name</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <button class="btn btn-info">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                <div class="clearfix"></div>
                <div class="table-responsive1">
                    <table class="table table-bordered table-striped table-hover">
                        <tbody>
                            <?php
                        if( count($mediafiles) === 0 ){
                            echo '<tr><td style="padding: 200px;text-align: center;">No data available in table</td></tr>';
                        }else {
                            foreach ($mediafiles as $mediafilelist) {
                                $user = $admin::$db->where('user_id',$mediafilelist->user_id)->getOne(T_USERS);
                                $context['bank'] = $mediafilelist;
                                $context['user'] = $admin->userData($user);
                                echo $admin->loadPage('bank-receipts/list');
                            }
                        }
                        ?>
                        </tbody>
                    </table>
                </div>
                
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
<script>

    function Wo_DeleteReceipt(receipt_id,user_id,photo_file) {
        if (confirm("Are you sure you want to delete this receipt?") == false) {
            return false;
        }
        hash_id = '';

        $.get(acpajax_url('delete_receipt'),{receipt_id: receipt_id, user_id: user_id, receipt_file: photo_file, hash_id: hash_id})
        .done(function( data ) {
            $('#ReceiptID_' + receipt_id).fadeOut(300, function() {
                $(this).remove();
            });
        });
    }

    function Wo_ApproveReceipt(receipt_id,photo_file) {
        if (confirm("Are you sure you want to approve this receipt?") == false) {
            return false;
        }
        hash_id = '';
        $('#ReceiptID_' + receipt_id).fadeOut(300, function() {
            $(this).remove();
        });
        $.get(acpajax_url('approve_receipt'),{f:'admin_setting', s:'approve_receipt', receipt_id: receipt_id, receipt_file: photo_file, hash_id: hash_id})
        .done(function( data ) {
            //window.location = window.location.href;
        });

    }

</script>