<?php if(!empty($context['user'])){ ?>

    <tr class="user-list" id="ReceiptID_<?php echo $context['bank']->id?>" data-receipt-id="<?php echo $context['bank']->id?>" style="width: 25%; float: left;margin-top: 20px;">
        <td style="border: 0px;text-align: center;display: block;">
            <a href="<?php echo $config['site_url'] . '/@' . $context['user']->username; ?>" target="_blank">
                <img src="<?php echo $context['user']->avatar;?>" class="setting-avatar" alt="<?php echo $context['user']->username;?> Profile Picture">
                <?php echo $context['user']->name; ?>
            </a>
            &nbsp;&nbsp;&nbsp;&nbsp;
            <span style="color:#607D8B;font-size: 11px;font-weight: bold;" class=" ajax-time" title="<?php echo date('c', strtotime($context['bank']->created_at)); ?>">
        </span>
            <hr>
            <a href="<?php echo media($context['bank']->receipt_file); ?>" target="_blank" >
                <img src="<?php echo media($context['bank']->receipt_file); ?>" class="setting-avatar" style="min-width: 197px;object-fit: cover;height: 250px;">
            </a>
            <div class="clearfix"></div>
            <p><b><?php //echo $wo['mediafilelist']->mode;?></b></p>
            <p>
                <?php echo $context['bank']->description;?> =
                <b><?php echo $config['currency'] .' '.$context['bank']->price;?></b>
            </p>
            <?php if((int)$context['bank']->approved == 0){?>
            <div class="row">
                <div class="col-md-6">
                    <button  style="float: right;" onclick="Wo_DeleteReceipt(<?php echo $context['bank']->id?>,<?php echo $context['bank']->user_id?>,'<?php echo $context['bank']->receipt_file?>');" type="button" class="btn btn-danger waves-effect waves-light" style="margin: 0 auto;display: block;">DELETE</button>
                </div>
                <div class="col-md-6">
                    <button style="float: left;" onclick="Wo_ApproveReceipt(<?php echo $context['bank']->id?>,'<?php echo $context['bank']->receipt_file?>');" type="button" class="btn btn-success waves-effect waves-light" style="margin: 0 auto;display: block;">APPROVE</button>
                </div>
            </div>
            <?php } else{ ?>
        <b style="color:darkgreen;">Approved <?php echo $context['bank']->approved_at; ?></b>
    <?php } ?>
        </td>
    </tr>
<?php } ?>