
<div class="block-header">
    <h2 class="breadcrumb">Languages <i class="material-icons">keyboard_arrow_right</i> Add New Language & Keys</h2>
</div>
<div class="row">
    <div class="col-lg-6 col-md-6">
        <div class="card">
            <div class="header">
                <h2>Add New Language</h2>
            </div>
            <div class="body">
                <div class="add-newlang-form-alert">
                    
                </div>
                <form class="add-newlang-form" method="POST">
                    <div class="form-group form-float">
                        <div class="form-line">
                            <input type="text" id="lang" name="lang" class="form-control">
                            <label class="form-label">Language Name <small>Use only english letters, no spaces allowed. E.g: russian</small></label>
                        </div>
                    </div>
                    <div>Note: This may take up to 5 minutes.</div>
                    <button type="submit" class="btn btn-primary m-t-15 waves-effect">Add Language</button>
                </form>
            </div>
        </div>
    </div>
    <div class="col-lg-6 col-md-6">
        <div class="card">
            <div class="header">
                <h2>Add New Key</h2>
            </div>
            <div class="body">
                <div class="add-langkey-form-alert"></div>
                <form class="add-langkey-form" method="POST">
                    <div class="form-group form-float">
                        <div class="form-line">
                            <input type="text" id="lang_key" name="lang_key" class="form-control">
                            <label class="form-label">Key Name <small>Use only english letters, no spaces allowed, example: this_is_a_key</small></label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-primary m-t-15 waves-effect">Add Key</button>
                </form>
            </div>
        </div>
    </div>
    <div class="clearfix"></div>
</div>
    <!-- #END# Vertical Layout -->
<script>

$(function() {
    $('form.add-newlang-form').ajaxForm({
        url: acpajax_url('new-lang'),
        dataType:'json',
        beforeSend: function() {
            $('form.add-newlang-form').find('button').text('Please wait..').attr('disabled', 'true');
        },
        success: function(data) {
            $("html, body").animate({ scrollTop: 0 }, "slow");
            if (data.status == 200) {        
                $('.add-newlang-form-alert').html($("<div>",{
                    class:'alert alert-success',
                    html: "<i class='fa fa-check'></i> Language successfully added"
                }));

                setTimeout(function () {
		            window.location.href = "<?php echo pxp_acp_link('manage-langs'); ?>";
		        }, 1000);
            }
            else if(data.status == 401){
                $('.add-newlang-form-alert').html($("<div>",{
                    class: 'alert alert-danger',
                    html: "<i class='fa fa-info'></i> Language name is invalid. Please enter a valid language name"
                }));
            }
            else if(data.status == 402){
                $('.add-newlang-form-alert').html($("<div>",{
                    class: 'alert alert-danger',
                    html: "<i class='fa fa-info'></i> This lang is already used."
                }));    
            }

            $('form.add-newlang-form').find('button').text('Add Language').removeAttr('disabled');
        }
    });

    $('form.add-langkey-form').ajaxForm({
        url: acpajax_url('new-key'),
        dataType: 'json',
        beforeSend: function() {
            $('form.add-langkey-form').find('button').text('Please wait..').attr('disabled', 'true');
        },
        success: function(data) {
            $("html, body").animate({ scrollTop: 0 }, "slow");
            if (data.status == 200) {
                $('.add-langkey-form-alert').html($("<div>",{
                    class:'alert alert-success',
                    html: "<i class='fa fa-check'></i> Key successfully added"
                }));

                setTimeout(function () {
                    window.location.href = "<?php echo pxp_acp_link('manage-langs'); ?>";
                }, 1000);
            }          
            else if(data.status == 401){
                $('.add-langkey-form-alert').html($("<div>",{
                    class:'alert alert-warning',
                    html: "<i class='fa fa-check'></i> Invalid language key characters. Please use only english letters"
                }));
            }
            else if(data.status == 402){
                $('.add-langkey-form-alert').html($("<div>",{
                    class:'alert alert-warning',
                    html: "<i class='fa fa-check'></i> Language key max length is 100 characters "
                }));
            }
            else if(data.status == 403){
                $('.add-langkey-form-alert').html($("<div>",{
                    class:'alert alert-warning',
                    html: "<i class='fa fa-check'></i> This key is already used, please use other one"
                }));
            }

            $('form.add-langkey-form').find('button').text('Add Key').removeAttr('disabled');
        }
    });
});
</script>