<div class="container-fluid">
    <div class="block-header">
        <h2>Design > Change Site Design</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="header">
                    <h2>Change Site Design</h2><br>
                </div>
                <div class="body">
                    
                    <form class="d-settings" method="POST">
                        <h4>Welcome Page</h4><hr>
                        <div class="d-settings-alert form-alert"></div>
                        <div class="input-group">
                           <span>Favicon</span>
                           <span class="btn btn-default btn-file">
                             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="#4caf50" class="feather feather-camera"><path d="M4,4H7L9,2H15L17,4H20A2,2 0 0,1 22,6V18A2,2 0 0,1 20,20H4A2,2 0 0,1 2,18V6A2,2 0 0,1 4,4M12,7A5,5 0 0,0 7,12A5,5 0 0,0 12,17A5,5 0 0,0 17,12A5,5 0 0,0 12,7M12,9A3,3 0 0,1 15,12A3,3 0 0,1 12,15A3,3 0 0,1 9,12A3,3 0 0,1 12,9Z"></path></svg>
                             <input type="file" id="favicon" accept="image/x-png, image/gif, image/jpeg" name="favicon">
                           </span>
                            <div class="form-group hidden" id="favicon-i">
                                <input type="text" class="form-control" readonly>
                            </div>
                        </div>
                        <div class="input-group">
                           <span>Background Image</span>
                           <span class="btn btn-default btn-file">
                             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="#4caf50" class="feather feather-camera"><path d="M4,4H7L9,2H15L17,4H20A2,2 0 0,1 22,6V18A2,2 0 0,1 20,20H4A2,2 0 0,1 2,18V6A2,2 0 0,1 4,4M12,7A5,5 0 0,0 7,12A5,5 0 0,0 12,17A5,5 0 0,0 17,12A5,5 0 0,0 12,7M12,9A3,3 0 0,1 15,12A3,3 0 0,1 12,15A3,3 0 0,1 9,12A3,3 0 0,1 12,9Z"></path></svg>
                             <input type="file" id="background-image" accept="image/x-png, image/gif, image/jpeg" name="background-image">
                           </span>
                            <div class="form-group hidden" id="background-image-i">
                                <input type="text" class="form-control" readonly>
                            </div>
                        </div>
                        <div class="input-group">
                           <span>Welcome Banner</span>
                           <span class="btn btn-default btn-file">
                             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="#4caf50" class="feather feather-camera"><path d="M4,4H7L9,2H15L17,4H20A2,2 0 0,1 22,6V18A2,2 0 0,1 20,20H4A2,2 0 0,1 2,18V6A2,2 0 0,1 4,4M12,7A5,5 0 0,0 7,12A5,5 0 0,0 12,17A5,5 0 0,0 17,12A5,5 0 0,0 12,7M12,9A3,3 0 0,1 15,12A3,3 0 0,1 12,15A3,3 0 0,1 9,12A3,3 0 0,1 12,9Z"></path></svg>
                             <input type="file" id="banner" accept="image/x-png, image/gif, image/jpeg" name="banner">
                           </span>
                            <div class="form-group hidden" id="banner-i">
                                <input type="text" class="form-control" readonly>
                            </div>
                        </div>
                        <br><h4>Header</h4><hr>
                        <div class="input-group">
                           <span>Logo (470x75)</span>
                           <span class="btn btn-default btn-file">
                             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="#4caf50" class="feather feather-camera"><path d="M4,4H7L9,2H15L17,4H20A2,2 0 0,1 22,6V18A2,2 0 0,1 20,20H4A2,2 0 0,1 2,18V6A2,2 0 0,1 4,4M12,7A5,5 0 0,0 7,12A5,5 0 0,0 12,17A5,5 0 0,0 17,12A5,5 0 0,0 12,7M12,9A3,3 0 0,1 15,12A3,3 0 0,1 12,15A3,3 0 0,1 9,12A3,3 0 0,1 12,9Z"></path></svg>
                             <input type="file" id="logo" accept="image/x-png, image/gif, image/jpeg" name="logo">
                           </span>
                            <div class="form-group hidden" id="logo-i">
                                <input type="text" class="form-control" readonly>
                            </div>
                        </div>
                        <div class="input-group">
                            <span>Light Logo (470x75)</span>
                            <span class="btn btn-default btn-file">
                             <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="#4caf50" class="feather feather-camera"><path d="M4,4H7L9,2H15L17,4H20A2,2 0 0,1 22,6V18A2,2 0 0,1 20,20H4A2,2 0 0,1 2,18V6A2,2 0 0,1 4,4M12,7A5,5 0 0,0 7,12A5,5 0 0,0 12,17A5,5 0 0,0 17,12A5,5 0 0,0 12,7M12,9A3,3 0 0,1 15,12A3,3 0 0,1 12,15A3,3 0 0,1 9,12A3,3 0 0,1 12,9Z"></path></svg>
                             <input type="file" id="light-logo" accept="image/x-png, image/gif, image/jpeg" name="light-logo">
                           </span>
                            <div class="form-group hidden" id="logo-li">
                                <input type="text" class="form-control" readonly>
                            </div>
                        </div>
                        <div>Please make sure to clean your browser cache after changing the design settings.</div>
                        <input type="hidden" name="hash_id" value="">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6">
            <div class="card">
                <div class="header">
                    <h2>Change Design Config</h2><br>
                </div>
                <div class="body">
                    
                    <form class="form general-settings-form" method="POST">
                        <h4>Welcome Page</h4><hr>
                        <div class="d-settings-alert form-alert"></div>

                        <label for="show_welcome_background">Show Background Image</label>
                        <div class="form-group">
                            <input type="radio" name="show_welcome_background"  value="on" id="show_welcome_background-enabled" <?php echo ($config['show_welcome_background'] == 'on') ? 'checked': '';?>>
                            <label for="show_welcome_background-enabled">Enabled</label>
                            <input type="radio" name="show_welcome_background" id="show_welcome_background-disabled" value="off" <?php echo ($config['show_welcome_background'] == 'off') ? 'checked': '';?>>
                            <label for="show_welcome_background-disabled" class="m-l-20">Disabled</label>
                        </div> 

                        <label for="show_welcome_banner">Show Welcome Banner</label>
                        <div class="form-group">
                            <input type="radio" name="show_welcome_banner"  value="on" id="show_welcome_banner-enabled" <?php echo ($config['show_welcome_banner'] == 'on') ? 'checked': '';?>>
                            <label for="show_welcome_banner-enabled">Enabled</label>
                            <input type="radio" name="show_welcome_banner" id="show_welcome_banner-disabled" value="off" <?php echo ($config['show_welcome_banner'] == 'off') ? 'checked': '';?>>
                            <label for="show_welcome_banner-disabled" class="m-l-20">Disabled</label>
                        </div> 

                        <label for="show_welcome_banner">Welcome Banner Title</label>
                        <div class="form-group">
                            <div class="form-line">
                                <input type="text" id="banner_title" name="banner_title" class="form-control" value="<?php echo ($config['banner_title']); ?>">
                                <label class="form-label">
                                    Welcome Banner Title
                                </label>
                            </div>
                        </div> 

                        <input type="hidden" name="hash_id" value="">
                        <button type="submit" class="btn btn-primary m-t-15 waves-effect">Save</button>
                    </form>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
    <!-- #END# Vertical Layout -->
<script>
$(function() {
    $("#background-image").change(function () {
         var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
         $("#background-image-i input").val(filename);
         $("#background-image-i").removeClass('hidden');
    });
    $("#favicon").change(function () {
         var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
         $("#favicon-i input").val(filename);
         $("#favicon-i").removeClass('hidden');
    });
    $("#banner").change(function () {
         var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
         $("#banner-i input").val(filename);
         $("#banner-i").removeClass('hidden');
    });
    $("#logo").change(function () {
         var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
         $("#logo-i input").val(filename);
         $("#logo-i").removeClass('hidden');
    });
    $("#light-logo").change(function () {
        var filename = $(this).val().replace(/C:\\fakepath\\/i, '');
        $("#logo-li input").val(filename);
        $("#logo-li").removeClass('hidden');
    });
    var form_d_settings = $('form.d-settings');
    form_d_settings.ajaxForm({
        url: acpajax_url('update_design_setting'),
        beforeSend: function() {
            form_d_settings.find('.waves-effect').text('Please wait..');
        },
        success: function(data) {
            if (data.status == 200) {
                form_d_settings.find('.waves-effect').text('Save');
                $(form_d_settings).find('div.form-alert').scroll2().html($('<div>',{
                    class:'alert alert-success',
                    text:'Settings has been updated successfully'
                }));
                setTimeout(function(){
                    form_d_settings.find('div.form-alert .alert').slideUp('fast',function(){
                        $(this).remove(); 
                    })    
                },3000);
            }
        }
    });

    var gsform = $("form.general-settings-form");
    gsform.ajaxForm({
        url: acpajax_url('general-settings'),
        type: 'POST',
        dataType: 'json',
        beforeSubmit: function(arr,form){
            $(form).find('button[type=submit]').text('Please wait.').attr('disabled', 'true');
        },
        success: function(data, status, xhr, form){
            if (data.status == 200) {
                $(form).find('div.form-alert').scroll2().html($('<div>',{
                    class:'alert alert-success',
                    text:'Settings has been updated successfully'
                }));
                setTimeout(function(){
                    gsform.find('div.form-alert .alert').slideUp('fast',function(){
                        $(this).remove(); 
                    })    
                },1000);
            }
            else{
                $(form).find('div.form-alert').scroll2().html($('<div>',{
                    class:'alert alert-warning',
                    text: data.error
                }));
            }

            gsform.find('button[type=submit]').text('Save').removeAttr('disabled');
        }
    });
});
</script>
<style>
.colorpicker {
    z-index: 0 !important;
}
.btn-file input[type=file]{
        position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    opacity: 0;
    outline: none;
    background: #fff;
    cursor: inherit;
    display: block;
}
.btn-file {
    position: relative;
    overflow: hidden;
    margin-left: 25px;
}
</style>
