<tr id="list-<?php echo($cd['challenge']['id']); ?>" data-id="<?php echo($cd['challenge']['id']); ?>">
	<td>
		<input type="checkbox" id="check-video-<?php echo($cd['challenge']['id']); ?>" class="delete-checkbox filled-in"><label for="check-video-<?php echo($cd['challenge']['id']); ?>"></label>
	</td>
	<td>
		<span>
			<?php echo($cd['challenge']['id']);?>
		</span>
	</td>
	<td>
		<a href="javascript:void(0)" 
			class="edit-challenge" 
			data-id="<?php echo($cd['challenge']['id']); ?>"
			data-title="<?php echo($cd['challenge']['name']); ?>"
			data-info="<?php echo($cd['challenge']['info']); ?>"
			data-start_date="<?php echo($cd['challenge']['start_date']); ?>"
			data-close_date="<?php echo($cd['challenge']['close_date']); ?>"
			data-status="<?php echo($cd['challenge']['status']); ?>"
			data-pro_level="<?php echo($cd['challenge']['pro_level']); ?>"
			data-community="<?php echo($cd['challenge']['community']); ?>"
			data-exclusive="<?php echo($cd['challenge']['exclusive']); ?>"
			data-entry_bonus="<?php echo($cd['challenge']['entry_bonus']); ?>"
			data-winner_prize="<?php echo($cd['challenge']['winner_prize']); ?>"> 
			<?php echo($cd['challenge']['name']); ?>
		</a>
	</td> 
	<td>
		<span>
			<?php echo $cd['challenge']['status'] == '1' ? 'Active' : 'Inactive'; ?>
		</span>
	</td>
	<td>
		<span>
			<?php echo $cd['challenge']['pro_level'] == '3' ? $cd['community']['title'].' Community' : ($cd['challenge']['pro_level'] == '2' ? 'Pro' : ($cd['challenge']['pro_level'] == '1' ? 'Standard' : 'Free')); ?>
		</span>
	</td>
	<td>
		<span>
			<?php echo $cd['exclusive']['title'] ? $cd['exclusive']['title'] : 'Not Exclusive'; ?>
		</span>
	</td>
	<td>
		<span>
			<?php echo(date('D d M Y', strtotime($cd['challenge']['start_date']))); ?>
			<b class="text-success">
				<?php echo(strtotime($cd['challenge']['start_date']) < strtotime('NOW') && strtotime($cd['challenge']['close_date']) > strtotime('NOW') ? 'Active' : ''); ?> 
			</b>
		</span>
	</td>
	<td>
		<span>
			<?php echo(date('D d M Y', strtotime($cd['challenge']['close_date']))); ?>
			<b class="text-danger"><?php echo(strtotime($cd['challenge']['close_date']) < strtotime('NOW') ? 'Ended' : ''); ?></b>
		</span>
	</td>
	<td>
		<button class="btn btn-danger waves-effect waves-light delete-challenge" data-id="<?php echo($cd['challenge']['id']); ?>">
			DELETE
		</button>
		<a href="<?php echo(chal2url($cd['challenge']['exclusive'], 'info')); ?>" class="btn btn-success waves-effect waves-light m-t-5">
			GOTO
		</a>
	</td>
</tr>
