<?php 
$page = (!empty($_GET['page-id'])) ? $_GET['page-id'] : 1;
$filter_keyword = (!empty($_GET['query'])) ? $admin::secure($_GET['query']) : '';
$filter_type    = '';
$admin::$db->pageLimit = 50;
$t_users = T_USERS;
$t_posts = T_POSTS;
$t_likes = T_POST_LIKES;

$postC = new Posts;
$context['_user'] = new User;

if (!empty($filter_keyword)) {

    if (is_numeric($filter_keyword)) {
        $admin::$db->where('p.`post_id`',"$filter_keyword"); 
    } else {
        $admin::$db->where('p.`description`',"%$filter_keyword%",'LIKE');
    }
    $fltc = $admin::$db->subQuery();
    $fltc->where('`name`',"%$filter_keyword%",'LIKE');
    $fltc->get(T_CHALLENGE, NULL, 'id');
    $admin::$db->where('p.`challenge_id`',$fltc, 'IN', 'OR');

    $admin::$db->where('challenge_id',"$filter_keyword",'=', 'OR'); 
} 

else {
    $admin::$db->where('p.`challenge_id`',"NULL", "!=");
}

$admin::$db->join("`$t_users` u",'p.`user_id` = u.`user_id`','INNER'); 
$posts = $admin::$db->orderBy('`likes`', 'DESC')->paginate("`$t_posts` p", $page,array(
    'p.`post_id`',
    'p.`time`',
    'u.`avatar`',
    'u.`username`',
    'u.`fname`',
    'u.`lname`',
    'p.`challenge_id`',
    'p.`approved`',
    "(SELECT COUNT(l.`id`) FROM `".$t_likes."` l WHERE l.`post_id` = p.`post_id` ) AS likes"
));

function getWinnersOnly($username)
{
    global $admin;
    $t_users = T_USERS;
    $t_posts = T_POSTS;
    $t_likes = T_POST_LIKES;
    $admin::$db->pageLimit = 3; 

    $admin::$db->where('p.`challenge_id`',"NULL", "!=")->where('u.`username`',$username); 
    $admin::$db->join("`$t_users` u",'p.`user_id` = u.`user_id`','INNER'); 
    $winners = $admin::$db->orderBy('`likes`', 'DESC')->getOne("`$t_posts` p", array(
        'p.`post_id`',
        'p.`time`',
        'u.`avatar`',
        'u.`username`',
        'u.`fname`',
        'u.`lname`',
        'p.`challenge_id`',
        'p.`approved`',
        "(SELECT COUNT(l.`id`) FROM `".$t_likes."` l WHERE l.`post_id` = p.`post_id` ) AS likes"
    ));//print_r($winners);
    return $winners;
}

$winners = $admin::$db->where('p.`challenge_id`',"NULL", "!=")->join("`$t_users` u",'p.`user_id` = u.`user_id`','INNER')->orderBy('likes', 'DESC')->groupBy("u.`username`, likes")->paginate("`$t_posts` p", 1, array( 
        'u.`username`', 
        "(SELECT COUNT(l.`id`) FROM `".$t_likes."` l WHERE l.`post_id` = p.`post_id` ) AS likes"
    ));

// echo$admin::$db->getLastQuery();

if (($page > $admin::$db->totalPages) && !empty($_GET['page-id'])) {
	header("Location: " . pxp_acp_link('manage-posts'));
	exit();
}
?>
<div class="clearfix">
    <div class="block-header">
        <h2 class="breadcrumb">Posts <i class="material-icons">keyboard_arrow_right</i> Challenge Entries</h2>
    </div>
    <!-- Winners -->
    <?php if (!empty($winners)): ?> 
        <div class="row clearfix">
        <?php $i=0; foreach ($winners as $key => $winner) {
            $i++;//print_r($winners);
            $context['winner']    = o2array(getWinnersOnly($winner->username));// print_r($context['winner']);
            $context['status']    = ($i == 1 ? 'WINNER' : ($i == 2 ? 'FIRST RUNNER UP' : 'SECOND RUNNER UP'));
            $context['color']     = ($i == 1 ? 'green' : ($i == 2 ? 'blue' : 'amber'));
            $context['challenge'] = Generic::toArray($postC->challengeData($context['winner']['challenge_id']));
            echo $admin->loadPage('manage-challengers/winners');
        }?> 
        <hr class="bg-red"><br>
        </div>
    <?php endif; ?>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage Challenge posts</h2>
                </div>
                <div class="body">
                    <div class="clearfix">
                        <div class="col-md-6" style="margin-bottom:0;">
                            <form method="get" action="<?php echo pxp_acp_link('manage-challengers'); ?>">
                                <div class="row">
                                    <div class="col-md-8">
                                        <div class="form-group form-float">
                                            <div class="form-line">
                                                <input type="text" name="query" id="query" class="form-control" value="<?php echo($filter_keyword); ?>">
                                                <label class="form-label search-form">Search for ID, Post Description</label>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-lg-3 col-md-3">
                                        <button class="btn btn-info">Search</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>

                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover table-users">
                            <thead>
                                <tr>
                                    <th><input type="checkbox" id="check-all" class="filled-in check-all" ><label for="check-all"></label></th>
                                    <th>ID</th>
                                    <th>Challenge</th>
                                    <th>Publisher</th>
                                    <th><?php echo lang('post')?> Link</th>
                                    <th><?php echo lang('likes')?></th>
                                    <th>Posted</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                    if (!empty($posts)) {
                                        foreach ($posts as $key => $context['post']) {
                                            $context['post'] = o2array($context['post']);
                                            $context['challenge'] = Generic::toArray($postC->challengeData($context['post']['challenge_id']));
                                            echo $admin->loadPage('manage-challengers/list');
                                        }
                                    }
                                    else{
                                        echo $admin::createHtmlEl('tr',null,$admin::createHtmlEl('td',array(
                                            'colspan' => 8,
                                            'class' => 'empty-table',
                                        ),"No ".lang('posts')." found"));
                                    }  
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <?php if (!empty($posts)): ?>
                        <div class="clearfix">
                            <nav class="clearfix pagination-nav">
                                <div class="left col-md-5">
                                    <ul class="pagination">
                                        <li>
                                            <span>
                                                <?php echo "Showing $page out of " . $admin::$db->totalPages; ?>
                                            </span>
                                        </li>
                                    </ul>
                                </div>

                                <div class="clearfix col-md-7 right">
                                    <ul class="pagination pull-right">
                                        <li>
                                            <a href="<?php echo pxp_acp_link('manage-posts?page-id=1'); ?>" class="waves-effect" title='First Page'>
                                                <i class="material-icons">first_page</i>
                                            </a>
                                        </li>

                                        <?php if ($page > 1) { ?>
                                        <li>
                                            <a href="<?php echo pxp_acp_link('manage-posts?page-id=' . ($page - 1)); ?>" class="waves-effect" title='Previous Page'>
                                                <i class="material-icons">chevron_left</i>
                                            </a>
                                        </li>
                                        <?php } ?>

                                        <?php 
                                            $nums = 0;
                                            $nums_pages = ($page > 4) ? ($page - 4) : $page;
                                            for ($i=$nums_pages; $i <= $admin::$db->totalPages; $i++) { 
                                            if ($nums < 20) {?>

                                            <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                                <a href="<?php echo pxp_acp_link('manage-posts?page-id=' . ($i)); ?>" class="waves-effect">
                                                <?php echo $i ?>
                                                </a>
                                            </li>
                                            <?php } $nums++;
                                            }
                                        ?>

                                        <?php if ($admin::$db->totalPages > $page) { ?>
                                        <li>
                                            <a href="<?php echo pxp_acp_link('manage-posts?page-id=' . ($page + 1)); ?>" class="waves-effect" title="Next Page">
                                                <i class="material-icons">chevron_right</i>
                                            </a>
                                        </li>
                                        <?php } ?>

                                        <li>
                                            <a href="<?php echo pxp_acp_link('manage-posts?page-id=' . ($admin::$db->totalPages)); ?>" class="waves-effect" title='Last Page'>
                                                <i class="material-icons">last_page</i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    <?php endif; ?>
                </div>
                <div class="clearfix"></div>
                <button type="button" class="btn btn-info waves-effect delete-selected" disabled style="margin-bottom: 10px;margin-left: 10px;">DELETE SELECTED<span></span></button>
                <br>
                <div class="clearfix"></div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- #END# Vertical Layout -->
<div id="delete-modal" class="modal fade" role="dialog" data-id="">
    <div class="modal-dialog">
        <div class="modal-content modal-col-red">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">DELETE POST</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to continue? this action can't be undo</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link waves-effect delete-button" data-dismiss="modal" data-type="post">DELETE</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
</div>
<script>

$('.check-all').on('click', function(event) {
    $('input:checkbox').not(this).prop('checked', this.checked);
});
$('.delete-checkbox, .check-all').change(function(event) {
    $('.delete-selected').attr('disabled', false);
    $('.delete-selected').find('span').text(' (' + $('.delete-checkbox:checked').size() + ')');
});
$('.delete-selected').on('click', function(event) {
    event.preventDefault();
    data = new Array();
    $('td input:checked').parents('tr').each(function () {
        data.push($(this).attr('data-id'));
    });
    if (confirm('Are you sure that you want to delete the selected items(s)?')) {
        $('.delete-selected').attr('disabled', true);
        $('.delete-selected').text('Please wait..');
        $.post(acpajax_url('delete-multi-post'), {ids: data}, function () {
            alert('Items successfully deleted!');
            $.each( data, function( index, value ){
                $('#list-' + value).remove();
            });
            $('.delete-selected').text('DELETE SELECTED');
        });
    }
});
$(function () {
    $(document).on('click', '.delete-content',function(event) {
        event.preventDefault();
        $('#delete-modal .delete-button').attr('data-id', $(this).attr('data-id')); 
        $('#delete-modal').attr('data-id', $(this).attr('data-id')).modal('show');
    });
});

$(function () {
    $(document).on('click', '.approve-challenge',function(event) {
        event.preventDefault();

        var id        = $(this).attr('data-id');
        var action    = $(this).attr('data-action');
        var challenge = $(this).attr('data-challenge');

        $.post(acpajax_url('approve-challenge-entry'), {id:id,action:action,challenge:challenge}, function (response) {
            alert(response.message); console.log(response);
        });
        $(this).toggleClass('btn-warning btn-success');  
        if ($(this).attr('data-staction') == 'approve') {
            $(this).text('DISAPPROVE'); 
            $(this).attr('data-staction', 'disapprove'); 
            $(this).attr('data-action', '0'); 
        } else {
            $(this).text('APPROVE');  
            $(this).attr('data-staction', 'approve'); 
            $(this).attr('data-action', '1');  
        }
    });
});
</script>
