<?php 
$page = (!empty($_GET['page-id'])) ? $_GET['page-id'] : 1;
$admin::$db->pageLimit = 20;

$users = $admin::$db->orderBy('id', 'DESC')->paginate(T_BLACKLIST, $page);

if (($page > $admin::$db->totalPages) && !empty($_GET['page-id'])) {
	header("Location: " . pxp_acp_link('blacklist'));
	exit('sdsd');
}
?>
<div class="clearfix">
    <div class="block-header">
        <h2 class="breadcrumb">Users <i class="material-icons">keyboard_arrow_right</i> Black List users</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Ban IP, email or username</h2>
                    <br>
                    <p>Add any email, username or ip to prevent users from creating accounts within the blacklist.</p>
                </div>
                <div class="body">
                    <div class="clearfix">
                        <div class="col-md-6" style="margin-bottom:0;">
                            <div class="row">
                                <div class="col-md-8">
                                    <div class="form-group form-float">
                                        <div class="form-line">
                                            <input type="text" name="banned" id="banned" class="form-control">
                                            <label class="form-label search-form">IP Address, Email Address, or Username</label>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-lg-3 col-md-3">
                                    <button class="btn btn-info" onclick="addBan()">Ban</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover table-users">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Banned</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php 
                                    if (!empty($users)) {
                                        foreach ($users as $key => $context['user']) {
                                            // /$context['user'] = $admin->userData($context['user']);
                                            $context['user'] = o2array($context['user']);
                                            echo $admin->loadPage('blacklist/list');
                                        }
                                    }

                                    else{
                                        echo $admin::createHtmlEl('tr',null,$admin::createHtmlEl('td',array(
                                            'colspan' => 5,
                                            'class' => 'empty-table',
                                        ),"No Ban Found"));
                                    } 
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <?php if (!empty($users)): ?>      
                        <div class="clearfix">
                            <nav class="clearfix pagination-nav">
                                <div class="left col-md-5">
                                    <ul class="pagination">
                                        <li>
                                            <span>
                                                <?php echo "Showing $page out of " . $admin::$db->totalPages; ?>
                                            </span>
                                        </li>
                                    </ul>
                                </div>

                                <div class="clearfix col-md-7 right">
                                    <ul class="pagination pull-right">
                                        <li>
                                            <a href="<?php echo pxp_acp_link('blacklist?page-id=1'); ?>" class="waves-effect" title='First Page'>
                                                <i class="material-icons">first_page</i>
                                            </a>
                                        </li>

                                        <?php if ($page > 1) { ?>
                                        <li>
                                            <a href="<?php echo pxp_acp_link('blacklist?page-id=' . ($page - 1)); ?>" class="waves-effect" title='Previous Page'>
                                                <i class="material-icons">chevron_left</i>
                                            </a>
                                        </li>
                                        <?php } ?>

                                        <?php 
                                            $nums = 0;
                                            $nums_pages = ($page > 4) ? ($page - 4) : $page;
                                            for ($i=$nums_pages; $i <= $admin::$db->totalPages; $i++) { 
                                            if ($nums < 20) {?>

                                            <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                                <a href="<?php echo pxp_acp_link('blacklist?page-id=' . ($i)); ?>" class="waves-effect">
                                                <?php echo $i ?>
                                                </a>
                                            </li>
                                            <?php } $nums++;
                                            }
                                        ?>

                                        <?php if ($admin::$db->totalPages > $page) { ?>
                                        <li>
                                            <a href="<?php echo pxp_acp_link('blacklist?page-id=' . ($page + 1)); ?>" class="waves-effect" title="Next Page">
                                                <i class="material-icons">chevron_right</i>
                                            </a>
                                        </li>
                                        <?php } ?>

                                        <li>
                                            <a href="<?php echo pxp_acp_link('blacklist?page-id=' . ($admin::$db->totalPages)); ?>" class="waves-effect" title='Last Page'>
                                                <i class="material-icons">last_page</i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- #END# Vertical Layout -->
<div id="delete-modal" class="modal fade" role="dialog" data-id="">
    <div class="modal-dialog">
        <div class="modal-content modal-col-red">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">DELETE BAN</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to continue? this action can't be undo</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link waves-effect delete-button" data-dismiss="modal" data-type="ban" data-id="">DELETE</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
</div>
<script>
$(function () {
	$(document).on('click', '.delete-content',function(event) {
        event.preventDefault();
        $('#delete-modal .delete-button').attr('data-id', $(this).attr('data-id')); 
		$('#delete-modal').attr('data-id', $(this).attr('data-id')).modal('show');
	});
});
function addBan() {
    var value = $('#banned').val();
    $.post(acpajax_url('add_ban'), {value: value}, function(data, textStatus, xhr) {
        window.location.reload();
    });
}
</script>