<?php 
$page = (!empty($_GET['page-id'])) ? $_GET['page-id'] : 1;
$admin::$db->pageLimit = 30;
$t_users   = T_USERS;
$t_reports = T_USER_REPORTS;

$admin::$db->join("`$t_users` u1",'u1.`user_id` = r.`user_id`','INNER');
$admin::$db->join("`$t_users` u2",'u2.`user_id` = r.`profile_id`','INNER');

$reports = $admin::$db->orderBy('r.`id`', 'DESC')->paginate("`$t_reports` r",$page,array(
    'r.`id`',
    'r.`time`',
    'r.`type`',
    'u1.`username` u1_uname',
    'u1.`avatar` u1_uavatar',
    'u2.username u2_uname',
    'u2.user_id u2_id',
    'u2.avatar u2_uavatar'
));

if (($page > $admin::$db->totalPages) && !empty($_GET['page-id'])) {
	header("Location: " . pxp_acp_link('profile-reports'));
	exit();
}
?>
<div class="clearfix">
    <div class="block-header">
        <h2 class="breadcrumb">Reports <i class="material-icons">keyboard_arrow_right</i> Manage reports</h2>
    </div>
    <!-- Vertical Layout -->
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <div class="header">
                    <h2>Manage profile reports</h2>
                </div>
                <div class="body">
                    <div class="table-responsive1">
                        <table class="table table-bordered table-striped table-hover table-users">
                            <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Username</th>
                                    <th>Reported</th>
                                    <th>Type</th>
                                    <th>Profile</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                <?php
                                    if (!empty($reports)) {
                                        foreach ($reports as $key => $context['report']) {
                                            $context['report'] = o2array($context['report']);
                                            echo $admin->loadPage('profile-reports/list');
                                        }
                                    }
                                    else{
                                        echo $admin::createHtmlEl('tr',null,$admin::createHtmlEl('td',array(
                                            'colspan' => 6,
                                            'class' => 'empty-table',
                                        ),"No Reports found"));
                                    }  
                                ?>
                            </tbody>
                        </table>
                    </div>
                    <?php if (!empty($reports)): ?>
                        <div class="clearfix">
                            <nav class="clearfix pagination-nav">
                                <div class="left col-md-5">
                                    <ul class="pagination">
                                        <li>
                                            <span>
                                                <?php echo "Showing $page out of " . $admin::$db->totalPages; ?>
                                            </span>
                                        </li>
                                    </ul>
                                </div>

                                <div class="clearfix col-md-7 right">
                                    <ul class="pagination pull-right">
                                        <li>
                                            <a href="<?php echo pxp_acp_link('profile-reports?page-id=1'); ?>" class="waves-effect" title='First Page'>
                                                <i class="material-icons">first_page</i>
                                            </a>
                                        </li>

                                        <?php if ($page > 1) { ?>
                                        <li>
                                            <a href="<?php echo pxp_acp_link('profile-reports?page-id=' . ($page - 1)); ?>" class="waves-effect" title='Previous Page'>
                                                <i class="material-icons">chevron_left</i>
                                            </a>
                                        </li>
                                        <?php } ?>

                                        <?php 
                                            $nums = 0;
                                            $nums_pages = ($page > 4) ? ($page - 4) : $page;
                                            for ($i=$nums_pages; $i <= $admin::$db->totalPages; $i++) { 
                                            if ($nums < 20) {?>

                                            <li class="<?php echo ($page == $i) ? 'active' : ''; ?>">
                                                <a href="<?php echo pxp_acp_link('profile-reports?page-id=' . ($i)); ?>" class="waves-effect">
                                                <?php echo $i ?>
                                                </a>
                                            </li>
                                            <?php } $nums++;
                                            }
                                        ?>

                                        <?php if ($admin::$db->totalPages > $page) { ?>
                                        <li>
                                            <a href="<?php echo pxp_acp_link('profile-reports?page-id=' . ($page + 1)); ?>" class="waves-effect" title="Next Page">
                                                <i class="material-icons">chevron_right</i>
                                            </a>
                                        </li>
                                        <?php } ?>

                                        <li>
                                            <a href="<?php echo pxp_acp_link('profile-reports?page-id=' . ($admin::$db->totalPages)); ?>" class="waves-effect" title='Last Page'>
                                                <i class="material-icons">last_page</i>
                                            </a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    <?php endif; ?>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
    </div>
</div>
<!-- #END# Vertical Layout -->
<div id="delete-modal" class="modal fade" role="dialog" data-id="">
    <div class="modal-dialog">
        <div class="modal-content modal-col-red">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">DELETE USER</h4>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to continue? this action can't be undo</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-link waves-effect delete-button" data-dismiss="modal" data-type="user" data-id="">DELETE</button>
                <button type="button" class="btn btn-link waves-effect" data-dismiss="modal">CLOSE</button>
            </div>
        </div>
    </div>
</div>
<script>
$(function () {
	$(document).on('click', '.delete-report',function(event) {
		event.preventDefault();
        var rid = $(this).data('id');
		$.post(acpajax_url('delete-report'), {id: rid,t:1}, function(data) {});
        $('[data-report="'+rid+'"]').slideUp(400,function(){
            $(this).remove();
        });
	});

    $(document).on('click', '.delete-content',function(event) {
        event.preventDefault();
        $('#delete-modal .delete-button').attr('data-id', $(this).attr('data-id')); 
        $('#delete-modal').attr('data-id', $(this).attr('data-id')).modal('show');
    });
});
</script>