<div class="form-group" style="margin-bottom: 0px;">
    <div class="form-lins">
        <label class="form-lasbel"><?php echo ucfirst($cd['lang']['key_']); ?></label>
        <textarea style="resize: none;" name="<?php echo $cd['lang']['key_']; ?>" id="<?php echo $cd['lang']['key_']; ?>" class="form-control" cols="20" rows="2" data-editable="<?php echo $cd['lang']['is_editale']; ?>"><?php echo $cd['lang']['lang_vlaue'] ?></textarea>
    </div>
</div>