<tr>
	<td>
		<span>
			<?php echo($cd['lid']);?>
		</span>
	</td>
	<td>
		<span>
			<?php echo($cd['lkey']);?>
		</span>
	</td>
	<td id="edit-lang-<?php echo($cd['lid']);?>">
		<span>
			<?php echo($cd['lval']);?>
		</span>
	</td>
	<td>
		<button type="button" class="btn btn-default waves-effect btn-edit-lang-key m-r-20" data-id="<?php echo($cd['lid']);?>" data-key="<?php echo($cd['lkey']);?>">
			EDIT
		</button>
	</td>
</tr>